# Generated by Django 4.2.2 on 2025-01-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookTitle',
            new_name='title',
        ),
    ]
