# Generated by Django 4.2.2 on 2025-01-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_booktitle_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='release_date',
            new_name='release_year',
        ),
    ]
